project_id = "vqjbphahfitbaqcpqfyh"

[functions.generate-flashcards]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.solve-homework]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false
